name: hemant job
# trigger poin
on: 
  push: 
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

# creating jobs

jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps: # what exactly you want to run in ubuntu machine
    - name: taking code from my repo
      uses: actions/checkout@v5
      with:
        ref: dryrun-aws 
      # terrafor installing 
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3
      # running some commands 
    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version
        whoami
        ls -a
        terraform version
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentails@v5.1.0
      with: 
        aws-access-key-id: ${{secret.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secret.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-southeast-2

    - name: verify aws connection
      run: |
        echo "checking with command"
        aws s3 ls
        
  build-job:
  infra-job:

